<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OrderTracking.Domain\OrderTracking.Domain.csproj" />
    <ProjectReference Include="..\..\src\OrderTracking.Infrastructure\OrderTracking.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\OrderTracking.Api\OrderTracking.Api.csproj" />
  </ItemGroup>

</Project>
